version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CoffeeService-Orders"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g6w7e87w2r1q"
s3_prefix = "CoffeeService-Orders"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
